name: build-aks

on:
  push:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build with Make
        run: make

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: aks
          path: ./aks
