name: build-aks

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build with Make
        run: make

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: aks
          path: ./aks

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: aks
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./aks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
